name: batteries
description: A Very Good App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  manager:
    path: D://FLUTTER//applications//apps//manager
  states_rebuilder: ^6.4.0
  hive_flutter: ^1.1.0
  get: ^4.6.6

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7 
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
