name: batteries
description: A Very Good App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^4.0.0-dev.2
  intl: ^0.18.1
  isar: ^4.0.0-dev.13
  isar_flutter_libs: ^4.0.0-dev.13
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  manager:
    path: D://FLUTTER//applications//packages//manager

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7 
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
