name: applications

packages:
  - apps/**
scripts:
  build all apps:
    exec: flutter build apk
  install all apks:
    exec: adb install build\app\outputs\flutter-apk\app-release.apk
command:
  bootstrap:
    environment:
      sdk: ">=3.2.0 <4.0.0"
      flutter: ">=3.19.2 <4.0.0"
    dependencies:
      cupertino_icons: ^1.0.6
      json_annotation: ^4.8.1
      freezed_annotation: ^2.4.1
      flutter_native_splash: ^2.3.10
      hive: ^4.0.0-dev.2
      isar: ^4.0.0-dev.13
      isar_flutter_libs: ^4.0.0-dev.13
      states_rebuilder: ^6.4.0
      package_info_plus: ^5.0.1
      path_provider: ^2.1.2
      flex_color_scheme: ^7.3.1
      font_awesome_flutter: ^10.7.0
      uuid: ^4.3.3
    dev_dependencies:
      build_runner: ^2.4.8
      json_serializable: ^6.7.1
      freezed: ^2.4.7
      very_good_analysis: ^5.1.0
