name: apps

description: riverpod
publish_to: 'none'
version: 2.0.0+1
homepage: https://github.com/kmcite2020/applications
environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  hive_flutter:
  uuid:
  file_picker:
  material_design_icons_flutter: 
  font_awesome_flutter:
  google_fonts: ^4.0.3
  colornames: 
  equatable:
  shared_preferences: 
  intl:
  mockito:
  path_provider:
  collection:
  flex_color_scheme: ^6.1.2
  states_rebuilder: ^6.2.0
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test:
  


flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/fonts/
