name: chat_gpt
description: "A new Flutter project. ChatGPT UI Clone for my fortpolio."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  states_rebuilder: ^6.4.0 
  json_annotation: ^4.8.1 
  freezed_annotation: ^2.4.1
  path_provider: ^2.1.2 
  uuid: ^4.3.3
  manager:
    path: D://FLUTTER//applications//apps//manager
   
dev_dependencies:
  build_runner: ^2.4.8 
  freezed: ^2.4.7
  json_serializable: ^6.7.1 
flutter:
  uses-material-design: true
