name: chat_gpt
description: "A new Flutter project. ChatGPT UI Clone for my fortpolio."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 
  states_rebuilder: ^6.4.0 
  package_info_plus: ^5.0.1 
  colornames: 
  flutter_native_splash: ^2.3.10   
  path_provider: ^2.1.2 
  uuid: ^4.3.3 
  dynamic_color: 
  hive_flutter: ^1.1.0 
  json_annotation: ^4.8.1 
  freezed_annotation: ^2.4.1
  manager:
    path: D://FLUTTER//applications//apps//manager   
dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7 
  json_serializable: ^6.7.1
  analyzer: ^6.4.1 

flutter:
  uses-material-design: true
