name: beseech
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  states_rebuilder: ^6.4.0
  colornames:
  intl:
  flex_color_scheme: ^7.3.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  manager:
    path: D://FLUTTER//applications//apps//manager
  clay_containers: ^0.3.2
  dots_indicator: ^2.1.2
  google_fonts: ^5.1.0
dev_dependencies:
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/
    # - shorebird.yaml


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    # image_path: "path/to/image.png"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"
  windows:
    generate: true
    # image_path: "path/to/image.png"
    # icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    # image_path: "path/to/image.png"
# dart run flutter_launcher_icons
# flutter pub add isar isar_flutter_libs path_provider
# flutter pub add -d isar_generator build_runner