name: derma_handbook
description: A new Flutter project.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  share_plus: ^7.1.0
  flex_color_scheme: ^7.3.1
  colornames: ^0.1.0
  file_picker: ^5.5.0
  path_provider: ^2.1.2
  flutter_native_splash: ^2.3.10
  states_rebuilder: ^6.4.0
  uuid: ^4.3.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1 
  manager:
    path: D://FLUTTER//applications//apps//manager
    

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1
  freezed: ^2.4.7 
flutter:
  uses-material-design: true
  assets:
    - lib/assets/splash.jpg
    - lib/assets/data/
flutter_native_splash:
  image: "lib/assets/icon.png"
  color: "#000000"
  background_image: "lib/assets/splash.jpg"

flutter_launcher_icons:
  android: "launcher_icon"
  # ios: true
  image_path: "lib/assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/assets/icon.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "lib/assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/assets/icon.png"
# dart run flutter_native_splash:create
# dart run flutter_launcher_icons