name: roster_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  extensions:
    path: ..//..//packages//extensions
  manager:
    path: ..//..//packages//manager 
  freezed_annotation: any
  colornames: ^0.1.0
  build_runner: ^2.4.8
  json_annotation: any
  json_serializable: ^6.7.1

dev_dependencies:
  freezed: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
