name: roster_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive: ^4.0.0-dev.2
  isar: ^4.0.0-dev.13
  isar_flutter_libs: ^4.0.0-dev.13

  manager:
    path: D://FLUTTER//applications//apps//manager
  states_rebuilder: ^6.4.0
  flex_color_scheme: ^7.3.1
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  build_runner: ^2.4.8
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
