name: rebuilder_docs
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  states_rebuilder: ^6.3.0
  flutter_native_splash: ^2.3.3
  google_fonts: ^6.1.0
  uuid: ^4.1.0
  flex_color_scheme: ^7.3.1
  path_provider: ^2.1.1
  json_annotation: ^4.8.1
  colornames: ^0.1.0
  hive_flutter: ^1.1.0
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_native_splash:
  image: "assets/app_icon.png"
  color: "#000000"
  background_image: "assets/app_icon.png"

flutter_launcher_icons:
  android: "launcher_icon"
  # ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"
# dart run flutter_native_splash:create
# dart run flutter_launcher_icons