name: hmis
description: A new Flutter project.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: any
  json_annotation: any
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.5.0
  sizer: ^2.0.15
  flutter_native_splash: ^2.3.1
  path_provider: ^2.1.1
  states_rebuilder: ^6.4.0
  hive_flutter: ^1.1.0
  uuid: ^4.1.0
  manager:
    path: D://FLUTTER//applications//packages//manager
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  freezed: any
  json_serializable: any
  build_runner: ^2.3.3
  flutter_lints: any

flutter:
  assets:
    - assets/
    # - shorebird.yaml
  uses-material-design: true
flutter_native_splash:
  image: "assets/hospital.png"
  color: "#000000"
  background_image: "assets/hospital_bg.png"

flutter_launcher_icons:
  android: "launcher_icon"
  # ios: true
  image_path: "assets/hospital.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/hospital.png"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/hospital.png"
    icon_size: 72 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/hospital.png"
# dart run flutter_native_splash:create
# dart run flutter_launcher_icons