name: manager
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  states_rebuilder: ^6.4.0
  uuid: ^4.3.3
  hive_flutter: ^1.1.0
  package_info_plus: ^5.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  build_runner: ^2.4.9
  flutter_markdown: ^0.7.1

dev_dependencies:
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
