name: manager
description: "A new State Management Project"
publish_to: 'none' 
version: 2.0.0+0
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  states_rebuilder: ^6.4.0
  package_info_plus: ^5.0.1
  freezed: any
  freezed_annotation: ^2.4.1
  build_runner: any
  colornames: any
  flutter_native_splash: ^2.3.10
  path_provider: ^2.1.2
  uuid: ^4.3.3
  dynamic_color: ^1.7.0
  hive_flutter: ^1.1.0

dev_dependencies:
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
