name: manager
description: "A new State Management Project"
publish_to: 'none' 
version: 2.0.0+0
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  states_rebuilder: ^6.4.0
  package_info_plus: ^5.0.1
  build_runner: 
  colornames: 
  flutter_native_splash: ^2.3.10 
  path_provider: ^2.1.2 
  uuid: ^4.3.3 
  dynamic_color: ^1.7.0
  hive_flutter: ^1.1.0 
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1 
dev_dependencies:
  json_serializable: ^6.7.1
  freezed: ^2.4.7 
  analyzer: ^6.4.1 

flutter:
  uses-material-design: true
