name: manager
description: "A new State Management Project"
publish_to: 'none' 
version: 2.0.0+0
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  states_rebuilder: ^6.4.0
  package_info_plus: ^5.0.1
  freezed: 
  freezed_annotation: 
  build_runner: 
  colornames: 
  flutter_native_splash: 
  path_provider: 
  uuid: 
  dynamic_color: ^1.7.0
  hive_flutter: 

dev_dependencies:
  analyzer: 

flutter:
  uses-material-design: true
