name: manager
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  states_rebuilder: ^6.4.0
  package_info_plus: ^5.0.1
  hive: ^4.0.0-dev.2
  # isar: ^4.0.0-dev.13
  # isar_flutter_libs: ^4.0.0-dev.13
  freezed: any
  freezed_annotation: ^2.4.1
  build_runner: any
  colornames: any
  flutter_native_splash: ^2.3.10
  path_provider: ^2.1.2
  uuid: ^4.3.3
  dynamic_color: ^1.7.0

dev_dependencies:
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
