name: memories
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  manager:
    path: D://FLUTTER//manager
  json_annotation: ^4.8.1
  uuid: ^4.3.3
  file_picker: ^8.0.0+1
  freezed_annotation: ^2.4.1
  freezed: ^2.5.2
  package_info_plus: ^5.0.1
  bitsdojo_window: ^0.1.6
  hive_flutter: ^1.1.0
dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
