name: smc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flex_color_scheme: ^7.3.1
  manager:
    path: D://FLUTTER//applications//apps//manager
  states_rebuilder: ^6.4.0
  isar: ^4.0.0-dev.13
  isar_flutter_libs: ^4.0.0-dev.13
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
dev_dependencies:
  build_runner: ^2.4.8
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"
flutter:
  uses-material-design: true
# dart run flutter_launcher_icons